import { Transaction } from "@/types/transactions";

export const transactionTypes: Transaction["type"][] = ["income", "expense"];
export const transactionCategories: Transaction["category"][] = [
  "salary",
  "food",
  "transport",
  "shopping",
  "bills",
  "entertainment",
  "other",
];
export const dummyTransactions: Transaction[] = [
  {
    id: "1",
    amount: 25000,
    type: "income",
    category: "salary",
    description: "August Salary",
    date: "2026-08-01",
  },
  {
    id: "2",
    amount: 450,
    type: "expense",
    category: "food",
    description: "Grocery Shopping",
    date: "2026-08-03",
  },
  {
    id: "3",
    amount: 850,
    type: "expense",
    category: "bills",
    description: "Electricity Bill",
    date: "2026-08-05",
  },
  {
    id: "4",
    amount: 300,
    type: "expense",
    category: "transport",
    description: "Transportation",
    date: "2026-08-07",
  },
  {
    id: "5",
    amount: 1200,
    type: "expense",
    category: "shopping",
    description: "Clothes",
    date: "2026-08-10",
  },
  {
    id: "6",
    amount: 650,
    type: "expense",
    category: "entertainment",
    description: "Cinema & Dinner",
    date: "2026-08-14",
  },
  {
    id: "7",
    amount: 2500,
    type: "income",
    category: "other",
    description: "Freelance Project",
    date: "2026-08-18",
  },
  {
    id: "8",
    amount: 700,
    type: "expense",
    category: "food",
    description: "Restaurant",
    date: "2026-08-20",
  },
  {
    id: "9",
    amount: 400,
    type: "expense",
    category: "transport",
    description: "Taxi",
    date: "2026-08-22",
  },
  {
    id: "10",
    amount: 1500,
    type: "expense",
    category: "shopping",
    description: "Home Supplies",
    date: "2026-08-25",
  },
];